// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.2
// source: donut.proto

package donut

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Donutins_Search_FullMethodName = "/donut.Donutins/Search"
)

// DonutinsClient is the client API for Donutins service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DonutinsClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*BaseReply, error)
}

type donutinsClient struct {
	cc grpc.ClientConnInterface
}

func NewDonutinsClient(cc grpc.ClientConnInterface) DonutinsClient {
	return &donutinsClient{cc}
}

func (c *donutinsClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, Donutins_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DonutinsServer is the server API for Donutins service.
// All implementations must embed UnimplementedDonutinsServer
// for forward compatibility
type DonutinsServer interface {
	Search(context.Context, *SearchRequest) (*BaseReply, error)
	mustEmbedUnimplementedDonutinsServer()
}

// UnimplementedDonutinsServer must be embedded to have forward compatible implementations.
type UnimplementedDonutinsServer struct {
}

func (UnimplementedDonutinsServer) Search(context.Context, *SearchRequest) (*BaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedDonutinsServer) mustEmbedUnimplementedDonutinsServer() {}

// UnsafeDonutinsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DonutinsServer will
// result in compilation errors.
type UnsafeDonutinsServer interface {
	mustEmbedUnimplementedDonutinsServer()
}

func RegisterDonutinsServer(s grpc.ServiceRegistrar, srv DonutinsServer) {
	s.RegisterService(&Donutins_ServiceDesc, srv)
}

func _Donutins_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonutinsServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Donutins_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonutinsServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Donutins_ServiceDesc is the grpc.ServiceDesc for Donutins service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Donutins_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donut.Donutins",
	HandlerType: (*DonutinsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Donutins_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "donut.proto",
}
